version: '3'

services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5433:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data  
    web:
        build: .
        command: bin/rails server
        volumes:
        - .:/shopping_cart
        ports:
        - "3000:3000"
        depends_on:
        - db
        - redis        
    test:
        build: .
        command: sh -c "bin/rails db:create && bundle exec rspec"
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis 
        environment:
            - DATABASE_URL= postgresql://postgres:password@db:5432/shopping_cart
            - REDIS_URL= redis://redis:6379/0
volumes:
    postgres13:
    redis_data: